loader:
  - USA
  - FR
  - BE
  - GER
  - CH
  - NZL
  - AUS
  - KOR
  - JAP
  - ES
  - POR
  - IT

elasticsearch:
  clusterName: timelion-demo
  indexName: timelion-demo
  documentType: log
  nodes:
    - elk07:
      host: localhost
      port: 9300